BOT_TOKEN = "8985176381:AAH-jANqZrOvblwrKw4Qkiv69mNm2LozoRQ"

ADMIN_ID = 369031827

SCANNER_INTERVAL = 300

COINS = {
    "BTCUSDT": "BTCUSDT",
    "ETHUSDT": "ETHUSDT",
    "BNBUSDT": "BNBUSDT",
    "SOLUSDT": "SOLUSDT",
    "XRPUSDT": "XRPUSDT",
    "DOGEUSDT": "DOGEUSDT",
    "ADAUSDT": "ADAUSDT",
    "TRXUSDT": "TRXUSDT"
}
