BOT_TOKEN = "8995261480:AAE_eOkCX1gOH0DWE6h9MmGWythKDrYz-lM"

ADMIN_ID = 369031827

SCANNER_INTERVAL = 300

COINS = {
    "BTCUSDT": "BTCUSDT",
    "ETHUSDT": "ETHUSDT",
    "BNBUSDT": "BNBUSDT",
    "SOLUSDT": "SOLUSDT",
    "XRPUSDT": "XRPUSDT",
    "DOGEUSDT": "DOGEUSDT",
    "ADAUSDT": "ADAUSDT",
    "TRXUSDT": "TRXUSDT"
}
