BOT_TOKEN = "8995261480:AAE_eOkCX1gOH0DWE6h9MmGWythKDrYz-lM"

ADMIN_ID = 369031827

SCANNER_INTERVAL = 300

COINS = {
    "BTCUSDT": "BINANCE",
    "ETHUSDT": "BINANCE",
    "BNBUSDT": "BINANCE",
    "SOLUSDT": "BINANCE",
    "XRPUSDT": "BINANCE",
    "DOGEUSDT": "BINANCE",
    "ADAUSDT": "BINANCE",
    "TRXUSDT": "BINANCE"
}
